import "dotenv/config";

import { connectDB, disconnectDB } from "../config/db.js";
import { Brand } from "../models/Brand.js";
import { Category } from "../models/Category.js";
import { Product } from "../models/Product.js";
import { User } from "../models/User.js";
import { slugify } from "../utils/slugify.js";
import { brands, categories, products } from "./data.js";

const FRESH = process.argv.includes("--fresh");

async function run() {
  await connectDB();

  if (FRESH) {
    console.log("  🧹  --fresh: clearing products, brands, categories and users");
    await Promise.all([
      Product.deleteMany({}),
      Brand.deleteMany({}),
      Category.deleteMany({}),
      User.deleteMany({}),
    ]);
  } else {
    await Promise.all([
      Product.deleteMany({}),
      Brand.deleteMany({}),
      Category.deleteMany({}),
    ]);
  }

  const brandDocs = await Brand.insertMany(
    brands.map((b) => ({ ...b, slug: slugify(b.name) }))
  );
  const categoryDocs = await Category.insertMany(
    categories.map((c) => ({ ...c, slug: slugify(c.name) }))
  );

  const brandBySlug = Object.fromEntries(brandDocs.map((b) => [b.slug, b]));
  const categoryBySlug = Object.fromEntries(categoryDocs.map((c) => [c.slug, c]));

  const docs = [];
  const seen = new Set();

  for (const p of products) {
    const brand = brandBySlug[p.brandSlug];
    const category = categoryBySlug[p.categorySlug];

    if (!brand) {
      console.warn(`  ⚠️   skipping "${p.name}" — unknown brand "${p.brandSlug}"`);
      continue;
    }
    if (!category) {
      console.warn(`  ⚠️   skipping "${p.name}" — unknown category "${p.categorySlug}"`);
      continue;
    }

    let slug = slugify(p.name);
    while (seen.has(slug)) slug = `${slug}-2`;
    seen.add(slug);

    docs.push({
      ...p,
      slug,
      brand: brand._id,
      brandName: brand.name,
      brandSlug: brand.slug,
      category: category._id,
      categorySlug: category.slug,
      accent: brand.accent,
      // Generated by `npm run images` at the repo root. Replace any file in
      // frontend/public/products/ with a real photo of the same name and the
      // storefront picks it up with no code change.
      images: [`/products/${slug}.webp`],
    });
  }

  await Product.insertMany(docs);

  // A demo admin so you can hit the protected routes straight away.
  const adminEmail = "admin@mobile.com.bd";
  if (!(await User.findOne({ email: adminEmail }))) {
    await User.create({
      name: "Store Admin",
      email: adminEmail,
      phone: "01711111111",
      password: "admin123",
      role: "admin",
      isVerified: true,
    });
  }

  console.log(`
  ✅  Seed complete
      brands      ${brandDocs.length}
      categories  ${categoryDocs.length}
      products    ${docs.length}
      admin       ${adminEmail} / admin123
  `);

  await disconnectDB();
  process.exit(0);
}

run().catch(async (error) => {
  if (error?.isConnectionError) console.error(error.message);
  else console.error("  ❌  Seed failed:", error);
  await disconnectDB();
  process.exit(1);
});
